name: Test source code
on: [push, workflow_dispatch]
jobs:
  build:
    name: Build and use venv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Print Python version
        run: python -c "import sys; print(sys.version)"
      - name: Build venv
        run: python -m venv venv
      - name: Set source to the venv
        run: source venv/bin/activate
      - name: Success
        run: exit 0
